### PR TITLE
Final Submission - Capstone React Project.

### PR DESCRIPTION
**Pull request by skyv26**
# # Milestone - Complete Project

[Benjamin Kisenge](https://github.com/iambenkis) and [Aakash Verma](https://github.com/skyv26) both did complete this group project as per requirements. We have implemented the features as following: 

- Followed the `GitFlow`.
- Created setup for the `React` Project.
- Installed the `react`, `react-redux` and `redux-logger` and `react-router` library.
- Created the `components` folder and added the different components.
- Added the `pages` folder for implementing *Multi-Page Application*.
- Added the `React-RouterV6` `BrowserRouter`, `Routes` and `Route` and Navigation.
- Added the `reducer` for **rockets** and **missions**.
- Did the testing for `pages` (Rockets, Missions and App.js)
- Created the `configurationStore` for *combining* the reducers.
- Used the `createAsyncThunk` and `createSlice` methods for creating reducer.
- Implemented the `Rockets` **Reservation** and **Cancel Reservation** function.
- Implemented the `Missions` **Joined** and **Leave** functionality.
- Added the `profile` page for displaying the `Reserved` Rockets and `Joined Missions` status.
- Added the *Badges* for displaying labels on either rockets or missions, reserved or Joined.
- Followed the best-practices.
- Implemented the `DRY` code as much as possible.
- Fetch the data from **API** Once.
- Updated the `[README.md]` file with content and video presentation
  - [Video Presentation Link](https://drive.google.com/file/d/1OvcgvOwVF8OjLKD56DP0nb_wvVzStoxq/view?usp=sharing)
- Added the minimal styles using CSS.

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
Hi @skyv26, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🎉 🎉 🎉 
- Requirements well implemented
- Code looks organized

## Required Changes ♻️
- You have failing test cases. Please fix those and submit for another review
Screenshot from 2022-10-07 19-05-02


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
@afanimartin Thank you for pointing out the issue . 👍🏻

**Review by Ismailco — APPROVED** [review]
### Hi @skyv26, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

cr-approve

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by skyv26** [comment]
### @Ismailco Thank you very much ❤️

**Pull request merged**
